#!/usr/bin/env bash

if [[ $EUID -ne 0 ]]; then
  echo "must run as root"
  exit 1
fi

echo "fuse-xfstests version $(git rev-parse --short HEAD)"
date -u

# Test root dir

R=/tmp/check-cntr
export FSTYP=fuse.cntr
export TEST_DEV=$R/testdev
export TEST_DIR=$R/testdir
export SCRATCH_DEV=$R/scratchdev
export SCRATCH_MNT=$R/scratchdir
export RUST_BACKTRACE=1

mounts=($TEST_DIR $TEST_DEV $SCRATCH_MNT $SCRATCH_DEV)

for m in "${mounts[@]}"; do
  umount "$m"
  while mountpoint -q "$m"; do
    echo "umount '$m'"
    umount "$m"
  done
done

rm -rf "$R"
mkdir -p "${mounts[@]}"

mount -t tmpfs -o size=5G none $SCRATCH_DEV
mount -t tmpfs -o size=5G none $TEST_DEV
#mount /dev/zvol/zroot/xfs-scratch $SCRATCH_DEV
#mount /dev/zvol/zroot/xfs-test $TEST_DEV

mount | grep "$R"

bash ./check $*
